import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useState } from 'react'
import RigthDrawer from '../components/RigthDrawer'
import CartList from '../components/CartList/CartList'
import ProductCard from '../components/ProductCard'

const Home: NextPage = () => {
  const [showCartList, setShowCartList] = useState(false)
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='text-center text-9xl'>:D</h1>
    </>
  )
}

export default Home
