import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useState } from 'react'
import RigthDrawer from '../components/RigthDrawer'
import CartList from '../components/CartList/CartList'
import Modal from '../components/Modal'
import ProductCard from '../components/ProductCard'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [showCartList, setShowCartList] = useState(false)
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='flex gap-3 flex-row w-full'>
        <ProductCard product={{ id: 1, name: 'TV', price: 1 }} />
        <ProductCard product={{ id: 2, name: 'iphone', price: .99 }} />
      </div>
      <RigthDrawer isOpen={showCartList} onClose={setShowCartList} title="Carrito">
        <>
          <CartList />
          <button
            type="button"
            className="inline-flex w-full justify-center rounded-md border border-transparent dark:bg-primary-dark bg-primary px-4 py-2 text-base font-medium shadow-sm focus:outline-none focus:ring-2 focus:ring-sky-500 focus:ring-offset-2 sm:ml-3 sm:w-auto sm:text-sm"
            onClick={() => router.push('/buy')}
          >
            Comprar
          </button>
          <button
            type="button"
            onClick={() => setShowCartList(false)}
            className="inline-flex w-full justify-center rounded-md border border-gray-300 dark:bg-secondary-dark bg-secondary px-4 py-2 text-base font-medium shadow-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm"
          >
            Cancelar
          </button>
        </>
      </RigthDrawer>
      <div className='w-full dark:bg-surface-dark bg-surface p-4 absolute bottom-0 left-0'>
        <button className='rounded p-2 dark:bg-primary-dark bg-primary ml-auto' onClick={() => setShowCartList(true)}>Finalizar compra</button>
      </div>
    </>
  )
}

export default Home
